### ISSUE TITLE
preview text  line breaks not preserve whole words

### ISSUE THREAD

**Issue by faye1225** [imzbf/md-editor-rt#72]
preview text  line breaks not preserve whole words
and-> a nd
<img width="495" alt="image" src="https://user-images.githubusercontent.com/56664035/235475803-7c83cd02-e080-4ea1-a176-d0b80a7316e7.png">

try add `style={{ wordBreak: 'break-word' }}`,but not work

**Comment by imzbf** [comment]
The priority of default is higher than this, add style into your project:

```css
.md-editor-preview {
  word-break: break-word;
}
```
